name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16", "1.15"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: |
          make test
